# Generated by Django 4.2.7 on 2023-11-29 14:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Matter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MatterDate", models.DateField()),
                ("MatterSubject", models.CharField(max_length=255)),
                ("MatterDetail", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "MatterStatus",
                    models.CharField(
                        choices=[("Active", "Active"), ("Closed", "Closed")],
                        max_length=10,
                    ),
                ),
                (
                    "FileId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fs.fileinfo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MatterType", models.CharField(max_length=50)),
                ("MatterDesc", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SenderShortName", models.CharField(max_length=30)),
                ("SenderPost", models.CharField(max_length=100)),
                ("SenderOffice", models.CharField(max_length=100)),
                ("SenderPlace", models.CharField(max_length=100)),
                ("SenderShortNameH", models.CharField(max_length=30)),
                ("SenderPostH", models.CharField(max_length=100)),
                ("SenderOfficeH", models.CharField(max_length=100)),
                ("SenderPlaceH", models.CharField(max_length=100)),
                ("Pincode", models.CharField(max_length=10)),
                ("OfficeDefault", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Received",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ReceiveDate", models.DateField()),
                ("LetterNo", models.CharField(blank=True, max_length=50, null=True)),
                ("LetterDate", models.DateField()),
                ("LetterSubject", models.CharField(max_length=255)),
                ("LetterDetail", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "Urgency",
                    models.CharField(
                        choices=[
                            ("Normal", "Normal"),
                            ("Urgent", "Urgent"),
                            ("MostUrgent", "Most Urgent"),
                        ],
                        max_length=15,
                    ),
                ),
                ("DueDate", models.DateField(blank=True, null=True)),
                (
                    "ReceiveStatus",
                    models.CharField(
                        choices=[
                            ("Received", "Received"),
                            ("Issued", "Issued"),
                            ("Filed", "Filed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "FlowStatus",
                    models.CharField(
                        choices=[
                            ("Noting Put Up", "Noting Put Up"),
                            ("Noting Rejected", "Noting Rejected"),
                            ("Noting Corrected", "Noting Corrected"),
                            ("Noting Approved", "Noting Approved"),
                            ("Draft Put Up", "Draft Put Up"),
                            ("Draft Rejected", "Draft Rejected"),
                            ("Draft Corrected", "Draft Corrected"),
                            ("Draft Approved", "Draft Approved"),
                            ("Letter Put Up", "Letter Put Up"),
                            ("Letter Rejected", "Letter Rejected"),
                            ("Letter Corrected", "Letter Corrected"),
                            ("Letter Approved", "Letter Approved"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "MatterId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fs.matter"
                    ),
                ),
                (
                    "Sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fs.sender"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="matter",
            name="MatterType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="fs.mattertype"
            ),
        ),
    ]
