# Generated by Django 4.2.7 on 2023-11-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fs", "0003_alter_sender_pincode_alter_sender_senderofficeh_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matter",
            name="MatterStatus",
            field=models.CharField(
                choices=[("Active", "Active"), ("Closed", "Closed")],
                default="Active",
                max_length=10,
            ),
        ),
    ]
