# Generated by Django 4.2.7 on 2023-11-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fs", "0004_alter_matter_matterstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matter",
            name="MatterStatus",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active"), ("Closed", "Closed")],
                default="Active",
                max_length=10,
                null=True,
            ),
        ),
    ]
