# Generated by Django 4.2.2 on 2023-11-30 15:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0005_alter_matter_matterstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LetterDate', models.DateField(blank=True, null=True)),
                ('LetterSubject', models.CharField(max_length=255)),
                ('LetterBody', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Urgency', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('MostUrgent', 'Most Urgent')], max_length=15)),
                ('LetterType', models.CharField(choices=[('Draft', 'Draft'), ('Letter', 'Letter')], max_length=10)),
                ('LetterStatus', models.CharField(choices=[('Created', 'Created'), ('Verified', 'Verified')], max_length=10)),
                ('MatterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fs.matter')),
            ],
        ),
        migrations.CreateModel(
            name='LetterFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlowType', models.CharField(choices=[('Letter Put Up', 'Letter Put Up'), ('Draft Put Up', 'Draft Put Up'), ('Letter Put Up', 'Letter Put Up')], max_length=15)),
                ('TempFile', models.BooleanField(default=False)),
                ('NotingText', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('SuperiorAction', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Corrected', 'Corrected'), ('Rejected', 'Rejected')], max_length=15, null=True)),
                ('Remark', models.TextField(blank=True, null=True)),
                ('FlowStartTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('FlowEndTimeStamp', models.DateTimeField(blank=True, null=True)),
                ('TimeTaken', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('LetterId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fs.issueletter')),
                ('ReceiveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fs.received')),
            ],
        ),
    ]
