# Generated by Django 4.2.2 on 2023-11-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0006_issueletter_letterflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterflow',
            name='FlowType',
            field=models.CharField(choices=[('Noting Put Up', 'Noting Put Up'), ('Draft Put Up', 'Draft Put Up'), ('Letter Put Up', 'Letter Put Up')], max_length=15),
        ),
    ]
