# Generated by Django 4.2.2 on 2023-10-19 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acctname', models.CharField(max_length=50)),
                ('accttype', models.CharField(choices=[('Cash', 'Cash'), ('Bank Account', 'Bank Account'), ('Debt', 'Debt'), ('Advance', 'Advance'), ('Cards', 'Cards'), ('Wallet', 'Wallet')], max_length=50)),
                ('acctcategory', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=50)),
                ('acctdescription', models.TextField(blank=True, null=True)),
                ('openingbal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalfin.expensecategory')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trantype', models.CharField(choices=[('NRML', 'Normal'), ('Transfer', 'Transfer')], max_length=15)),
                ('trantcategory', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Investment', 'Investment'), ('Investment Liquidate', 'Investment Liquidate'), ('Debt', 'Debt'), ('Advance', 'Advance'), ('Adjustment', 'Adjustment')], max_length=20)),
                ('particular', models.TextField(blank=True, null=True)),
                ('credit_acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='personalfin.accountheads')),
                ('debit_acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_transactions', to='personalfin.accountheads')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalfin.expensecategory')),
                ('expense_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalfin.expensesubcategory')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personalfin.person')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('Kg', 'Kilogram'), ('Ltr', 'Liter'), ('Pcs', 'Piece')], max_length=5)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.TextField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalfin.transaction')),
            ],
        ),
    ]
