# Generated by Django 4.2.2 on 2023-11-07 17:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('BranchId', models.AutoField(primary_key=True, serialize=False)),
                ('BranchName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CorrStatus',
            fields=[
                ('CorrStatusId', models.AutoField(primary_key=True, serialize=False)),
                ('CorrStatus', models.CharField(max_length=50)),
                ('Detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('FileId', models.AutoField(primary_key=True, serialize=False)),
                ('FileType', models.CharField(choices=[('Corr', 'Correspondence'), ('Saction', 'Sanction'), ('L-Case', 'Legal Case'), ('CashConveyance', 'Cash Conveyance'), ('Duplicate', 'Duplicate'), ('DeceasedClaim', 'Deceased Claim'), ('CourtCase', 'Court Case'), ('Statement', 'Statement')], max_length=15)),
                ('FileName', models.CharField(max_length=255)),
                ('FileNo', models.TextField()),
                ('ActiveStatus', models.BooleanField(default=True)),
                ('OpenDate', models.DateField()),
                ('CloseDate', models.DateField(blank=True, null=True)),
                ('RelatedOffice', models.CharField(max_length=100)),
                ('FileLocation', models.TextField()),
                ('WordFile', models.FileField(upload_to='word_files/')),
            ],
        ),
        migrations.CreateModel(
            name='FlowType',
            fields=[
                ('FlowId', models.AutoField(primary_key=True, serialize=False)),
                ('FlowType', models.CharField(max_length=50)),
                ('Remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='IssueLetter',
            fields=[
                ('LetterId', models.AutoField(primary_key=True, serialize=False)),
                ('LetterSubject', models.CharField(max_length=255)),
                ('LetterText', models.CharField(max_length=255)),
                ('Urgency', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('MostUrgent', 'Most Urgent')], max_length=15)),
                ('FileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.fileinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Matter',
            fields=[
                ('MatterId', models.AutoField(primary_key=True, serialize=False)),
                ('MatterDate', models.DateField()),
                ('MatterSubject', models.CharField(max_length=255)),
                ('MatterDetail', models.TextField()),
                ('FileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.fileinfo')),
            ],
        ),
        migrations.CreateModel(
            name='MatterStatus',
            fields=[
                ('StatusId', models.AutoField(primary_key=True, serialize=False)),
                ('MatterStatus', models.CharField(max_length=50)),
                ('StatusDetail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MatterType',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('MatterType', models.CharField(max_length=50)),
                ('MatterDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Received',
            fields=[
                ('ReceiveId', models.AutoField(primary_key=True, serialize=False)),
                ('ReceiveDate', models.DateField()),
                ('LetterNo', models.TextField()),
                ('LetterDate', models.DateField()),
                ('LetterSubject', models.CharField(max_length=255)),
                ('LetterDetail', models.TextField()),
                ('Urgency', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('MostUrgent', 'Most Urgent')], max_length=15)),
                ('DueDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Senders',
            fields=[
                ('SenderId', models.AutoField(primary_key=True, serialize=False)),
                ('SenderPost', models.CharField(max_length=100)),
                ('SenderOffice', models.CharField(max_length=100)),
                ('SenderPlace', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MatterCorr',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Remark', models.TextField()),
                ('CorrStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.corrstatus')),
                ('IssueId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.issueletter')),
                ('MatterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.matter')),
                ('ReceiveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.received')),
            ],
        ),
        migrations.AddField(
            model_name='matter',
            name='MatterStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.matterstatus'),
        ),
        migrations.AddField(
            model_name='matter',
            name='MatterType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.mattertype'),
        ),
        migrations.CreateModel(
            name='LetterSender',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('SenderType', models.CharField(choices=[('Sender', 'Sender'), ('Receiver', 'Receiver'), ('Copyto', 'Copy To')], max_length=15)),
                ('SenderText', models.TextField()),
                ('LetterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.issueletter')),
            ],
        ),
        migrations.CreateModel(
            name='LetterFlow',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('NotingText', models.TextField()),
                ('SuperiorAction', models.CharField(choices=[('Approved', 'Approved'), ('Corrected', 'Corrected'), ('Rejected', 'Rejected')], max_length=15)),
                ('FlowStartTimeStamp', models.DateTimeField(default=datetime.datetime.now)),
                ('FlowEndTimeStamp', models.DateTimeField(blank=True, null=True)),
                ('TimeTaken', models.DurationField(blank=True, null=True)),
                ('FlowType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.flowtype')),
                ('LetterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.issueletter')),
                ('ReceiveId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.received')),
            ],
        ),
        migrations.CreateModel(
            name='LetterAttachment',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('AttachmentText', models.TextField()),
                ('LetterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eFile.issueletter')),
            ],
        ),
    ]
