# Generated by Django 4.2.2 on 2023-11-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='FileLocation',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='FileNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='DueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='LetterDetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='LetterNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
