# Generated by Django 4.2.2 on 2023-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eFile', '0002_alter_fileinfo_filelocation_alter_fileinfo_fileno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrstatus',
            name='Detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='WordFile',
            field=models.FileField(blank=True, null=True, upload_to='word_files/'),
        ),
        migrations.AlterField(
            model_name='flowtype',
            name='Remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='letterflow',
            name='NotingText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lettersender',
            name='SenderText',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matter',
            name='MatterDetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mattercorr',
            name='Remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matterstatus',
            name='StatusDetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mattertype',
            name='MatterDesc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
