# Generated by Django 4.2.2 on 2023-11-07 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eFile', '0003_alter_corrstatus_detail_alter_fileinfo_wordfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mattercorr',
            name='IssueId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eFile.issueletter'),
        ),
        migrations.AlterField(
            model_name='mattercorr',
            name='ReceiveId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eFile.received'),
        ),
    ]
