# Generated by Django 4.2.2 on 2023-11-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eFile', '0004_alter_mattercorr_issueid_alter_mattercorr_receiveid'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterflow',
            name='TempFile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='letterflow',
            name='LetterId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eFile.issueletter'),
        ),
        migrations.AlterField(
            model_name='letterflow',
            name='SuperiorAction',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Corrected', 'Corrected'), ('Rejected', 'Rejected')], max_length=15, null=True),
        ),
    ]
