# Generated by Django 4.2.2 on 2023-11-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eFile', '0005_letterflow_tempfile_alter_letterflow_letterid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueletter',
            name='LetterText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
