# Generated by Django 4.2.7 on 2023-11-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eFile", "0008_alter_received_letterdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileinfo",
            name="FileSl",
            field=models.IntegerField(default=0),
        ),
    ]
