# Generated by Django 4.2.7 on 2023-11-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eFile", "0009_fileinfo_filesl"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiveFlowStatus",
            fields=[
                ("Id", models.AutoField(primary_key=True, serialize=False)),
                ("Status", models.CharField(max_length=50)),
                (
                    "ReceiveId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="eFile.received"
                    ),
                ),
            ],
        ),
    ]
