# Generated by Django 4.2.7 on 2023-11-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eFile", "0010_receiveflowstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="received",
            name="Status",
            field=models.CharField(default="Letter Received", max_length=20),
        ),
    ]
