# Generated by Django 4.2.7 on 2023-11-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("eFile", "0011_received_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="received",
            name="Sender",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="eFile.senders",
            ),
        ),
    ]
