# Generated by Django 4.2.7 on 2023-11-28 17:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eFile", "0012_received_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="letterflow",
            name="NotingText",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
